# Generated by Django 4.2.5 on 2024-01-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital_maps',
            name='hos_id',
        ),
    ]
