# Generated by Django 4.2.5 on 2024-01-25 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_initial'),
        ('hospital_map', '0003_hospital_maps_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital_maps',
            name='hospital',
        ),
        migrations.AddField(
            model_name='hospital_maps',
            name='hos_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospitals'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospital_maps',
            name='lat',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
