# Generated by Django 4.2 on 2023-10-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0002_demo_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demo_user",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
