# Generated by Django 4.2 on 2023-10-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0004_alter_demo_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="demo_user1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("email", models.CharField(max_length=500)),
            ],
        ),
    ]
