# Generated by Django 4.2 on 2023-11-22 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_v_code_user_v_status"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="v_code",),
        migrations.RemoveField(model_name="user", name="v_status",),
    ]
