# Generated by Django 4.2.6 on 2024-01-27 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("district", "0001_initial"),
        ("division", "0001_initial"),
        ("station", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stations",
            unique_together={("name", "div_id", "dis_id")},
        ),
    ]
