# Generated by Django 4.2 on 2024-01-17 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("station", "0001_initial"),
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospitals",
            name="station_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="station.stations"
            ),
        ),
    ]
