# Generated by Django 4.2.5 on 2024-01-24 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitals',
            name='station_id',
        ),
    ]
