# Generated by Django 4.2.5 on 2024-01-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_hospitals_station_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitals',
            name='hos_image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
