# Generated by Django 4.2 on 2023-11-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("role", "0004_remove_role_name2"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="name2",
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
