# Generated by Django 4.2 on 2023-11-22 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("role", "0005_role_name2"),
    ]

    operations = [
        migrations.RemoveField(model_name="role", name="name2",),
    ]
